name: Android Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          sdkmanager --licenses

      - name: Install dependencies
        run: npm ci

      - name: Install NativeScript CLI
        run: npm install -g nativescript@8.9.2

      - name: Add Android platform
        run: ns platform add android

      - name: Validate Secrets
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          if [ -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "❌ Error: ANDROID_KEYSTORE_BASE64 secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" ]; then
            echo "❌ Error: ANDROID_KEYSTORE_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.ANDROID_KEY_ALIAS }}" ]; then
            echo "❌ Error: ANDROID_KEY_ALIAS secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.ANDROID_KEY_PASSWORD }}" ]; then
            echo "❌ Error: ANDROID_KEY_PASSWORD secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Decode Keystore
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android.keystore

      - name: Build Android Release APK
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: ns build android --release --key-store-path android.keystore --key-store-password "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --key-store-alias "${{ secrets.ANDROID_KEY_ALIAS }}" --key-store-alias-password "${{ secrets.ANDROID_KEY_PASSWORD }}"

      - name: Build Android Debug (PR)
        if: github.event_name == 'pull_request'
        run: ns build android

      - name: Build Android AAB (for Play Store)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ns build android --release --aab --key-store-path android.keystore --key-store-password "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" --key-store-alias "${{ secrets.ANDROID_KEY_ALIAS }}" --key-store-alias-password "${{ secrets.ANDROID_KEY_PASSWORD }}"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/**/*.apk
          retention-days: 30

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          name: android-aab
          path: platforms/android/app/build/outputs/bundle/**/*.aab
          retention-days: 30

      - name: Publish to Google Play Store
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: dev.iagocavalcante.eguadavaga
          releaseFiles: platforms/android/app/build/outputs/bundle/release/*.aab
          track: internal
          status: completed
          inAppUpdatePriority: 2